apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
